[2024-05-04T06:28:00.266+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo.read_csv scheduled__2022-12-20T00:00:00+00:00 [queued]>
[2024-05-04T06:28:00.286+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo.read_csv scheduled__2022-12-20T00:00:00+00:00 [queued]>
[2024-05-04T06:28:00.287+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-05-04T06:28:00.330+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): read_csv> on 2022-12-20 00:00:00+00:00
[2024-05-04T06:28:00.338+0000] {standard_task_runner.py:57} INFO - Started process 667 to run task
[2024-05-04T06:28:00.352+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'demo', 'read_csv', 'scheduled__2022-12-20T00:00:00+00:00', '--job-id', '851', '--raw', '--subdir', 'DAGS_FOLDER/dag_trial.py', '--cfg-path', '/tmp/tmp12j8yhi0']
[2024-05-04T06:28:00.353+0000] {standard_task_runner.py:85} INFO - Job 851: Subtask read_csv
[2024-05-04T06:28:00.450+0000] {task_command.py:410} INFO - Running <TaskInstance: demo.read_csv scheduled__2022-12-20T00:00:00+00:00 [running]> on host 08fc968d0c14
[2024-05-04T06:28:00.661+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='demo' AIRFLOW_CTX_TASK_ID='read_csv' AIRFLOW_CTX_EXECUTION_DATE='2022-12-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-20T00:00:00+00:00'
[2024-05-04T06:28:00.665+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_trial.py", line 19, in read_csv
    df = pd.read_csv('path/to/your/file.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'path/to/your/file.csv'
[2024-05-04T06:28:00.680+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=demo, task_id=read_csv, execution_date=20221220T000000, start_date=20240504T062800, end_date=20240504T062800
[2024-05-04T06:28:00.702+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 851 for task read_csv ([Errno 2] No such file or directory: 'path/to/your/file.csv'; 667)
[2024-05-04T06:28:00.719+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-05-04T06:28:00.743+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
