[2024-05-04T07:43:45.131+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nahoom.read_csv manual__2024-05-04T07:43:37.872859+00:00 [queued]>
[2024-05-04T07:43:45.147+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nahoom.read_csv manual__2024-05-04T07:43:37.872859+00:00 [queued]>
[2024-05-04T07:43:45.147+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-05-04T07:43:45.168+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): read_csv> on 2024-05-04 07:43:37.872859+00:00
[2024-05-04T07:43:45.175+0000] {standard_task_runner.py:57} INFO - Started process 2276 to run task
[2024-05-04T07:43:45.179+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nahoom', 'read_csv', 'manual__2024-05-04T07:43:37.872859+00:00', '--job-id', '957', '--raw', '--subdir', 'DAGS_FOLDER/nahoo.py', '--cfg-path', '/tmp/tmp0sy2iwit']
[2024-05-04T07:43:45.180+0000] {standard_task_runner.py:85} INFO - Job 957: Subtask read_csv
[2024-05-04T07:43:45.232+0000] {task_command.py:410} INFO - Running <TaskInstance: nahoom.read_csv manual__2024-05-04T07:43:37.872859+00:00 [running]> on host 08fc968d0c14
[2024-05-04T07:43:45.345+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nahoom' AIRFLOW_CTX_TASK_ID='read_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T07:43:37.872859+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-04T07:43:37.872859+00:00'
[2024-05-04T07:43:45.349+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/nahoo.py", line 20, in read_csv
    df = pd.read_csv('./data/20181024_d1_0830_0900.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: './data/20181024_d1_0830_0900.csv'
[2024-05-04T07:43:45.361+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=nahoom, task_id=read_csv, execution_date=20240504T074337, start_date=20240504T074345, end_date=20240504T074345
[2024-05-04T07:43:45.374+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 957 for task read_csv ([Errno 2] No such file or directory: './data/20181024_d1_0830_0900.csv'; 2276)
[2024-05-04T07:43:45.391+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-05-04T07:43:45.415+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
